server:
  port: 8081
  netty:
    connection-timeout: 20000
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/could_office?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 20010915tyht
    #spring自带的连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #连接最大存活时间
      max-lifetime: 180000
      #连接超时时间
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

#mybatis plus
mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: DNA.bean
  configuration:
    #关闭自动驼峰命名
    map-underscore-to-camel-case: false

#打印sql
logging:
  level:
    DNA.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24*7）
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer